apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
spec:
  selector:
    matchLabels:
      app: front
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
        - name: front
          image: youtubetrimmer.azurecr.io/youtube-trimmer/front:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: front
spec:
  type: LoadBalancer
  selector:
    app: front
  ports:
    - port: 80
      targetPort: 80